export const days = [
  { number: 1, date: '2019-12-1' },
  { number: 2, date: '2019-12-2' },
  { number: 3, date: '2019-12-3' },
  { number: 4, date: '2019-12-4' },
  { number: 5, date: '2019-12-5' },
  { number: 6, date: '2019-12-6' },
  { number: 7, date: '2019-12-7' },
  { number: 8, date: '2019-12-8' },
  { number: 9, date: '2019-12-9' },
  { number: 10, date: '2019-12-10' },
  { number: 11, date: '2019-12-11' },
  { number: 12, date: '2019-12-12' },
  { number: 13, date: '2019-12-13' },
  { number: 14, date: '2019-12-14' },
  { number: 15, date: '2019-12-15' },
  { number: 16, date: '2019-12-16' },
  { number: 17, date: '2019-12-17' },
  { number: 18, date: '2019-12-18' },
  { number: 19, date: '2019-12-19' },
  { number: 20, date: '2019-12-20' },
  { number: 21, date: '2019-12-21' },
  { number: 22, date: '2019-12-22' },
  { number: 23, date: '2019-12-23' },
  { number: 24, date: '2019-12-24' },
  { number: 25, date: '2019-12-25' },
]
export const deeds = [
  { deed: 'Write your mother a note', img: 'letter' },
  { deed: 'Spend 15 minutes with an animal', img: 'cat' },
  { deed: 'Walk to a store and just ask the cashier how their day is going', img: 'star' },
  { deed: 'Make a friend a cup of tea', img: 'tea' },
  { deed: 'Light a candle and say a prayer', img: 'candle' },
  { deed: 'Play with a youngster', img: 'kids' },
  { deed: 'Call your father, brother, uncle, nephew, grandpa or son', img: 'call' },
  { deed: 'Share a meal with someone, anyone.', img: 'food' },
  { deed: 'Walk until you find some trash and pick it up.', img: 'wallE' },
  { deed: 'Send a thank you to a business whose product you love', img: 'thankyou' },
  { deed: 'Write a review for a favorite restaurant', img: 'meal' },
  { deed: 'Text a loved one', img: 'text' },
  { deed: 'Make a social media post in praise of a friend', img: 'praise' },
  { deed: `Write down ten things you're grateful for`, img: 'grateful' },
  { deed: 'If you have a sibling, give them a hug. If not, give yourself one.', img: 'hug' },
  { deed: 'Give the next seated person you see a quick shoulder rub', img: 'snowman' },
  { deed: 'Pay the next person you see a compliment', img: 'heart' },
  { deed: 'Stand in line for coffee/tea/snack and offer the person behind you one', img: 'cupcake' },
  { deed: 'Bring someone you love a flower or a plant', img: 'flower' },
  { deed: 'Give a kiss', img: 'kiss' },
  { deed: 'Spend 15 minutes with a tree', img: 'tree' },
  { deed: 'Email a co worker about not work stuff', img: 'sleigh' },
  { deed: 'Call your bank and thank them for keeping your money safe', img: 'doge' },
  { deed: 'Put up a christmas decoration or lights', img: 'lights' },
  { deed: 'Go buy or make your favorite person a gift', img: 'gift' }
]
